use std::io::Write;

use super::*;

impl WeetGenerator {
    pub fn header<T: Write>(w: &mut PrettyWriter<T>) -> Result<(), Error> {
        w.write_lines(
            "
//
// This file was automatically generated by witx-codegen - Do not edit manually.
//

",
        )?;
        w.eob()?;
        Ok(())
    }
}
